const monsters = [
            
    { name: "Great Maccao" },
    { name: "Velocidrome" },
    { name: "Bulldrome" },
    { name: "Seltas" },
    { name: "Seltas Queen" },
    { name: "Arzuros" },
    { name: "Redhelm Arzuros" },
    { name: "Giadrome" },
    { name: "Gendrome" },
    { name: "Cephadrome" },
    { name: "Yian Kut-Ku" },
    { name: "Iodrome" },
    { name: "Kecha Wacha" },
    { name: "Lagombi" },
    { name: "Snowbaron Lagombi" },
    { name: "Gypceros" },
    { name: "Tetsucabra" },
    { name: "Drilltusk Tetsucabra" },
    { name: "Daimyo Hermitaur" },
    { name: "Stonefirst Hermitaur" },
    { name: "Volvidon" },
    { name: "Congalala" },
    { name: "Royal Ludroth" },
    { name: "Barroth" },
    { name: "Basarios" },
    { name: "Malfestio" },
    { name: "Nightcloak Malfestio" },
    { name: "Zamtrios" },
    { name: "Khezu" },
    { name: "Nerscylla" },
    { name: "Rathian" },
    { name: "Gold Rathian" },
    { name: "Dreadqueen Rathian" },
    { name: "Rathalos" },
    { name: "Silver Rathalos" },
    { name: "Dreadking Rathalos" },
    { name: "Nibelsnarf" },
    { name: "Plesioth" },
    { name: "Blangonga" },
    { name: "Lavasioth" },
    { name: "Shogun Ceanataur" },
    { name: "Rustrazor Ceanataur" },
    { name: "Najarala" },
    { name: "Nargacuga" },
    { name: "Silverwind Nargacuga" },
    { name: "Yian Garuga" },
    { name: "Deadeye Yian Garuga" },
    { name: "Uragaan" },
    { name: "Crystalbeard Uragaan" },
    { name: "Lagiacrus" },
    { name: "Zinogre" },
    { name: "Thunderlord Zingore" },
    { name: "Barioth" },
    { name: "Mizutsune" },
    { name: "Soulseer Mizutsune" },
    { name: "Astalos" },
    { name: "Boltreaver Astalos" },
    { name: "Gammoth" },
    { name: "Elderfrost Gammoth" },
    { name: "Glavenus" },
    { name: "Hellblade Glavenus" },
    { name: "Agnaktor" },
    { name: "Gore Magala" },
    { name: "Chaotic Gore Magala" },
    { name: "Seregios" },
    { name: "Duramboros" },
    { name: "Tigrex" },
    { name: "Grimclaw Tigrex" },
    { name: "Gravious" },
    { name: "Diablos" },
    { name: "Bloodbath Diablos" },
    { name: "Kirin" },
    { name: "Brachydios" },
    { name: "Raging Brachydios" },
    { name: "Shagaru Magala" },
    { name: "Valstrax" },
    { name: "Rajang" },
    { name: "Furious Rajang" },
    { name: "Deviljho" },
    { name: "Savage Deviljho" },
    { name: "Kushala Daora" },
    { name: "Chameleos" },
    { name: "Teostra" },
    { name: "Lao-Shan Lung" },
    { name: "Akantor" },
    { name: "Ukanlos" },
    { name: "Amatsu" },
    { name: "Nakarkos" },
    { name: "Ahtal-Neset" },
    { name: "Atahl-Ka" },
    { name: "Alatreon" },
    { name: "Fatalis" },
    { name: "Crimson Fatalis" },
    { name: "Old Fatalis" }
];